CREATE DATABASE IF NOT EXISTS admin_service;
CREATE DATABASE IF NOT EXISTS user_service;
CREATE DATABASE IF NOT EXISTS chat_service;
CREATE DATABASE IF NOT EXISTS auth_service;
CREATE DATABASE IF NOT EXISTS post_service;
CREATE DATABASE IF NOT EXISTS shop_service;
CREATE DATABASE IF NOT EXISTS community_service;