# 서비스의 포트를 랜덤으로 받습니다.
server:
  port: 0

# config 서버에서 설정 파일을 가져와 적용합니다
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
    name: user

info:
  app:
    name: My Application
    description: My Application is a Spring Boot application.
    version: 1.0.0


# 유레카 서버에 해당 서비스를 추가하는 설정입니다.
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

