spring:
  application:
    name: user
  profiles:
    active: service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: rootpass

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

