server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /${segment}

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/?(?<segment>.*), /${segment}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /${segment}

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat/?(?<segment>.*), /${segment}

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/?(?<segment>.*), /${segment}

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**
          filters:
            - RewritePath=/shop/?(?<segment>.*), /${segment}

        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
          filters:
            - RewritePath=/community/?(?<segment>.*), /${segment}
