@server = 192.168.0.57

### KAKAO 로그인페이지 요청
GET http://{{server}}:8080/auth/kakao/getRedirectUrl
### NAVER 로그인페이지 요청
GET http://{{server}}:8080/auth/naver/getRedirectUrl
### GOOGLE 로그인페이지 요청
GET http://{{server}}:8080/auth/google/getRedirectUrl

### KAKAO 사용자정보 가져오기 (getRedirectUrl 에서 받은 코드)
@code = "lutZmaHWq6UkKyXrkvGoOpdoliV2_slqAExF3lIa_Z6Xyrks6UeEuQAAAAQKKcjaAAABkJGljzXHP8VuE1ZNOQ"
GET http://{{server}}:8080/auth/kakao/login?code={{code}}

### Naver 사용자정보 가져오기 (getRedirectUrl 에서 받은 코드)
@code = "lutZmaHWq6UkKyXrkvGoOpdoliV2_slqAExF3lIa_Z6Xyrks6UeEuQAAAAQKKcjaAAABkJGljzXHP8VuE1ZNOQ"
GET http://{{server}}:8080/auth/kakao/login?code={{code}}

### Google 사용자정보 가져오기 (getRedirectUrl 에서 받은 코드)
@code = "4%2F0ATx3LY74NOlcj-Fx1i9gPZMIPpUdc8eBHjjKoBMGRWTpIloK5v7WZrHA4PSoLHfPxx04zQ"
GET http://{{server}}:8080/auth/kakao/login?code={{code}}





