# 서버 포트 지정
server:
  port: 0

# config 서버에서 설정 파일을 가져와 적용합니다
spring:
  application:
    name: chat-service
  config:
    import: optional:configserver:http://localhost:8888
    name: chat-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka